### ISSUE TITLE
PlotSquared World not yet selectable on DynMap

### ISSUE THREAD

**Issue by Gryph667** [TBMCPlugins/PluginConfigs#12]
Description: Plotworld should be available on Dynmap

Replication Steps:

1. Go to Dynmap
2. See it's not there

Results:

It isn't available

Expected:

Norbi pls

**Comment by Gryph667** [comment]
I attempted to add plotworld to the world.yml file directly to the server, as it's not in the config repos, reloaded the plug in, and checked the site. Was unavailable. Reverted the change, restarted the server, dynmap service restored.

**Comment by NorbiPeti** [comment]
Actually it's in the repo, it's just at the bottom for whatever reason. Your config change had a tab character in it, which yaml really doesn't like (again, for whatever reason).

**Comment by Gryph667** [comment]
And I copied those config elements from else where in the doc, so damn.
