### ISSUE TITLE
Remove Extra un-needed plugins

### ISSUE THREAD

**Issue by alisolarflare** [TBMCPlugins/PluginConfigs#21]
Plugins (40): CoreProtect, dynmap, DiscordPlugin, TerrainControl, OpenInv, VoidWorld, SmartSpawn, RandomTP, Votifier, ProtocolLib, LibsDisguises, SimpleBackup, FastAsyncWorldEdit, ChunkArchive, EnchantLimit, BlocksHub, PermissionsEx, ButtonCore, ButtonPresents, Vault, ChairStairs, WorldEdit, Essentials, ButtonWebsiteModule, PlotSquared, WorldGuard, Multiverse-Core, MythicMobs, Plot2Dynmap, Multiverse-Portals, LimitedCreative, EnjinMinecraftPlugin, ChestShop, Towny, Jobs, ChestShopNotifier, Movecraft, DungeonsXL, Dynmap-Towny, ButtonChat

Candidate plugins to remove:
Voidworld
SmartSpawn?
BlocksHub
LibsDisguises
WorldEdit (Don't we already have FAWE?)

Candidate plugins to merge:
ButtonPresents --> ButtonCore
RandomTP --> ButtonCore
ChunkArchive --> ButtonCore

Goal: Reduce complexity, reduce the amount of moving parts, reduce the connections between plugins to help us debug.

**Comment by Gryph667** [comment]
MythicMobs requires LibDisguises, documented dependence.

**Comment by NorbiPeti** [comment]
FAWE seems to require/install 'WorldEdit' as well. It might be done for plugins depending on the "WorldEdit" name. Either way, it breaks, if removed.

SmartSpawn I'm unsure about, but we may not need it. The /spawn command might be provided by it - we had to ditch EssentialsSpawn for some reason that would've provided it. But in case that's the sole purpose of it, it could be merged to ButtonCore.

BlocksHub is needed for FAWE-CoreProtect connection. Not necessarily a bad plugin idea (kind of like Vault), just not implemented widely.

**Comment by NorbiPeti** [comment]
With the current setup, we can't have NMS code in plugins that have other plugins depend on them. This means that ChunkArchive can't be merged into ButtonCore. We could merge it into ButtonPresents and use that as a home for NMS plugins.
![kep](https://user-images.githubusercontent.com/13187743/41998056-15105cba-7a5a-11e8-8b0b-f62631334256.png)

RandomTP -> ButtonCore - Finished in bc24df3

**Comment by NorbiPeti** [comment]
ChunkArchive -> ButtonPresents in TBMCPlugins/ButtonPresents#13

**Comment by NorbiPeti** [comment]
VoidWorld was added by iie in *2016*

```
I downloaded the voidworld generator for one reason, and this was to create a newbie spawn
```
- @iiegit

**Comment by alisolarflare** [comment]
Updating to V5 has pretty much forced us to do this. Problem solved lol.
