### ISSUE TITLE
On login, players get kicked for idling more than 10 minutes

### ISSUE THREAD

**Issue by alisolarflare** [TBMCPlugins/PluginConfigs#27]

**Comment by NorbiPeti** [comment]
It's mentioned in EssentialsX/Essentials#1928, it should be resolved in 2.15.1 when that's released.

**Comment by alisolarflare** [comment]
Well, I've idled on the server for like- 5 hours. So this bug aint here no more

**Comment by NorbiPeti** [comment]
Well, the AFK timer that kicked people is disabled now but it should be resolved anyways. :P
