### ISSUE TITLE
Set to use database in bukkit.yml

### ISSUE THREAD

**Issue by NorbiPeti** [TBMCPlugins/PluginConfigs#28]
Currently, it's storing SQLite databases per plugin.

Requirements:

* [x] Publish bukkit.yml
* [ ] Migrate data, even by exporting to SQL and importing to the DB, if needed

**Comment by alisolarflare** [comment]
@NorbiPeti What does the bukkit.yml have to do to with using SQL Databases? I noticed the [database] field in the bukkit.yml, but what kind of information would we gather using this?

**Comment by Gryph667** [comment]
Bukkit, I think, tracks all the plugins, and how they store their data.

**Comment by NorbiPeti** [comment]
Indeed, plugins (like LC) that use getDatabase() (IIRC) use this option. By default, it's an SQLite file in the plugin dir, but since we have a db server, why not use that.
