### ISSUE TITLE
Update Towny

### ISSUE THREAD

**Issue by alisolarflare** [TBMCPlugins/PluginConfigs#29]
TODO:

- [ ] Compile a list of all the config changes required to update from v0.92.0.0 to v0.92.0.12.
- [ ] Create a branch of the towny config file
- [ ] Commit the changes to the branch
- [ ] Review that all changes are made
- [ ] Re-compile a list of all the config changes
- [ ] Review that all changes are made
- [ ] Push config file to master, and upgrade Towny.

Benefits from updating Towny from v0.92.0.0 to v0.92.0.12

Code that prepares for 1.13's block ID change.
Multiple regen fixes (signs, slabs, mob spawners, stairs regen properly)

New Features
 - Nation Zones
 - Nation Spawn points
 - Vastly-improved Invite/Requests/Confirmations System
 - Limiting Outposts by Town and Nation Levels

New commands:
 - /town unclaim all 
 - /t set spawncost {amount}
 - /nation set board {message}
 - /plot evict

New config options:
 - minimum_amount_of_residents_in_town_for_outpost
 - global_town_settings.keep_inventory_on_death_in_town

More details in the [changelog](https://raw.githubusercontent.com/LlmDl/Towny/master/src/ChangeLog.txt).

**Comment by alisolarflare** [comment]
Note that this would mean we'll be on dev builds.

But the benefit of being on dev builds is that we will be able to interact a lot more with the Towny developer and request specific changes or report specific bugs a lot faster.

**Comment by alisolarflare** [comment]
Disadvantage

There will be *many* config changes necessary to upgrade from v0.92.0.0 to v0.92.0.12.

**Comment by alisolarflare** [comment]
http://towny.palmergames.com/dev-build-towny-advanced-0-92-0-11-1-11-2/

**Comment by alisolarflare** [comment]
TODO:

- [ ] Compile a list of all the config changes required to update from v0.92.0.0 to v0.92.0.12.
- [ ] Create a branch of the towny config file
- [ ] Commit the changes to the branch
- [ ] Review that all changes are made
- [ ] Re-compile a list of all the config changes
- [ ] Review that all changes are made
- [ ] Push config file to master, and upgrade Towny.

**Comment by Gryph667** [comment]
Aaaaand it's already tested on 1.13, should we update. At some point. In the future.

We did it Reddit!
