### ISSUE TITLE
Jobs Plugin Configuration

### ISSUE THREAD

**Issue by Gryph667** [TBMCPlugins/PluginConfigs#5]
To be configured via pull requests for deployment

**Comment by alisolarflare** [comment]
uhhh @Gryph667 what is the criteria for success for this issue?

**Comment by Gryph667** [comment]
You reviewing the entire config file, setting up all the changes in a PR, and it gets pushed to server. Things like the cool down, messing with numbers, etc. When it was installed, no changes were made from base install. As it currently stands with the players, everything is potentially changeable until our first established "baseline" config review. From there we can consider suggested changes on the forum.

**Comment by alisolarflare** [comment]
Incentivise items that can be sold in the market, decentivise items that can be farmed.
