### ISSUE TITLE
Towny Data Issue during explosion restore

### ISSUE THREAD

**Issue by Gryph667** [TBMCPlugins/PluginConfigs#64]
**Describe the bug**
After damage caused by creeper explosion, full block data related to stone variations is not used, meaning either it is being ignored or is not being captured.

**To Reproduce**
1. Place grid of blocks that utilize segmented block data, polished granite, acacia wood, diorite
2. Spawn in or lure creeper to area
3. Trigger creeper explosion over grid
4. Observe restore results

**Expected behavior**
All blocks are restored with their original states/values

**Actual behavior**
Stone block variants like polished granite are restored as base stone blocks instead

**Screenshots**
N/A

**Additional context**
N/A

**Comment by NorbiPeti** [comment]
Is it the explosion regen that happens automatically? Because that's part of Towny, not CoreProtect.

**Comment by Gryph667** [comment]
Yes it is. Interesting. From where does Towny get the block data?

**Comment by NorbiPeti** [comment]
I'm not sure, I see it has an option to take a snapshot, but that doesn't seem to affect explosion regen, it might just record the blocks when they're about to explode.

**Comment by NorbiPeti** [comment]
Still an issue, despite updating Towny a couple times in the meantime.

**Comment by NorbiPeti** [comment]
Fixed in [0.95.2.2](https://github.com/TownyAdvanced/Towny/releases/tag/0.95.2.2)
